### PR TITLE
Use math/rand global random source and deprecate PRNG global variable

### LINKED ISSUE #12: `rand.Rand` is not safe for concurrent use
I recently learned that random sources from `math/rand` are not safe for concurrent use. This is relevant to this package as the global `PRNG` (found in `rehttp.go`) does not have a mutex to guard against possible runtime panics.

[Relevant note from the docs](https://pkg.go.dev/math/rand#NewSource):

> Unlike the default [Source](https://pkg.go.dev/math/rand#Source) used by top-level functions, this source is not safe for concurrent use by multiple goroutines.

I have not attempted to reproduce a panic in this package directly, but I have found that they do occur when generating pseudorandom numbers concurrently:

```go
package main

import (
	"fmt"
	"math/rand"
	"sync"
	"time"
)

var src = rand.New(rand.NewSource(time.Now().UnixNano()))

func main() {
	var wg sync.WaitGroup

  for i := 0; i < 10; i++ {
		wg.Add(1)
		go func() {
			genRandom()
			wg.Done()
		}()
	}

	wg.Wait()	
  fmt.Println("done")
}

func genRandom() {
	for i := 0; i < 100_000_000; i++ {
		src.Intn(100)
	}
}
```

### PR DESCRIPTION
**Pull request by justinrixx**
closes #12

### CODE REVIEW

File: rehttp.go [hunk 1]
```diff
@@ -264,7 +269,24 @@ func ExpJitterDelay(base, max time.Duration) DelayFn {
 		exp := math.Pow(2, float64(attempt.Index))
 		top := float64(base) * exp
 		return time.Duration(
-			PRNG.Int63n(int64(math.Min(float64(max), top))),
+			rand.Int63n(int64(math.Min(float64(max), top))),
+		)
+	}
```
Comment (mna) [inline rehttp.go:274]: Let's have this function call `ExpJitterDelayWithRand` and pass `rand.Int63n` as the generator function, so that the algorithm is implemented only in one place.

File: rng_pre120.go [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+
+import (
+	"math/rand"
+	"time"
+)
+
+// Only seed the global random source on versions prior to 1.20 since
+// it's pre-seeded starting in 1.20
+func init() {
+	rand.Seed(time.Now().UnixNano())
```
Comment (mna) [inline rng_pre120.go:14]: I don't think the package should do this - the caller might have seeded the global source with a known value to get deterministic results. I think we should document on `ExpJitterDelay` that it assumes the global source has been properly seeded by the caller.

**Review by mna — COMMENTED** [review]
Thanks, looks good! Just a couple comments that should be addressed before merging.

**Comment by justinrixx** [comment]
All valid feedback. I should have recognized the duplication in `ExpJitterDelayWithRand`.

Updated now and ready for re-review.

**Review by mna — APPROVED** [review]
LGTM, thanks!
